export const SET_STARRED_BOARDS = "SET_STARRED_BOARDS";
export const SET_USER_DETAILS = "SET_USER_DETAILS";
export const SET_USER_IMAGE = "SET_USER_IMAGE";
export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";
export const SET_BOARDS_LIST = "SET_BOARDS_LIST";
export const SET_SEARCH = "SET_SEARCH";
export const SET_SEARCH_RESULTS = "SET_SEARCH_RESULTS";
