Tools.add(pencilTool);
Tools.add(rectangleTool);
Tools.add(textTool);
Tools.add(lineTool);
Tools.add(eraserTool);
Tools.add(ellipseTool);
Tools.add(handTool);
Tools.add(micTool);
Tools.change("Hand");
