version: '3'
services:
  frontend:
    image: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./frontend/src:/app/src:z
      - ./frontend/webpack.config.js:/app/webpack.config.js:z
      - ./frontend/package.json:/app/package.json:z
      - ./frontend/package-lock.json:/app/package-lock.json:z
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development

  authentication:
    image: authentication
    build:
      context: ./authentication
      dockerfile: Dockerfile
    container_name: authentication
    volumes:
      - ./authentication/src:/app/src:z
      - ./authentication/package.json:/app/package.json:z
      - ./authentication/package-lock.json:/app/package-lock.json:z
    ports:
      - "3001:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development

  nginx:
    image: nginx:latest
    ports:
      - "2000:8080"
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - authentication